# Generated by Django 5.0.7 on 2024-07-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Student"), (2, "Teacher"), (3, "Admin")],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="city",
        ),
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="roll",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="city",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="name",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subject",
        ),
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(default="B.Tech", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="enrollment_number",
            field=models.CharField(default="0000000000", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="linkedin_account",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("is_public", models.BooleanField(default=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.teacher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        default="images/default.jpg", upload_to="images/"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.role"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user",
            ),
        ),
    ]
