# Generated by Django 5.0.7 on 2024-07-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_role_remove_student_city_remove_student_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("information", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="course",
            old_name="teacher",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="course",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="objectives",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="page_picture",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="course",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="course",
            name="subscriptions",
            field=models.ManyToManyField(
                blank=True, related_name="subscribed_courses", to="myapp.student"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
