# Generated by Django 5.0.7 on 2024-08-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_section_rename_teacher_course_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="subscribed_courses",
            field=models.ManyToManyField(
                related_name="students_subscribed", to="myapp.course"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="subscriptions",
            field=models.ManyToManyField(
                blank=True, related_name="courses_subscribed", to="myapp.student"
            ),
        ),
    ]
